[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "H4mwUctvTzbQ7bgxceko6eoi3qYH9vmFqwMoPVQ9vf5T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
